document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/effects.css"><link rel="stylesheet" href="/career-blog.css">');
document.querySelector('header nav')?.insertAdjacentHTML('beforeend','<a href="/carreira.html">Carreira</a><a href="/blog.html">Blog</a><a href="/pos.html" style="color:#dfff00;font-weight:700">Pós ↗</a>');
document.querySelector('#sonhos')?.insertAdjacentHTML('beforebegin','<section class="career-preview"><small>[ 03 — CARREIRA ]</small><h2>Front-end com visão de produto,<br><em>IA e identidade visual.</em></h2><p>Bacharel em Ciência da Computação, pós-graduada em Inteligência Artificial e desenvolvedora freelancer desde 2023. Do briefing ao deploy, construo experiências responsivas com React, Next.js e JavaScript.</p><a class="career-link" href="/carreira.html">CONHECER MINHA TRAJETÓRIA ↗</a><a class="career-link" href="/blog.html">LER 40 POSTS TÉCNICOS ↗</a></section>');
const projects=[
['Radar Trader','Fintech · Dados B3 · Motion','Radar quantitativo de preço, volume, momento e risco.','radar-trend.png','https://cariotrade.vercel.app'],['ProgramaDora','IA · Editorial · Automação','Blog editorial com pesquisa e validação automatizadas.','programadora.png','https://programa-dora.vercel.app'],['BROTO','Finanças · Dados · Next.js','Plataforma de relatórios e leitura de mercado.','broto-real.png','https://plataforma.vercel.app'],['AstroMãe','IA · Voz · Python','Experiência conversacional com linguagem e voz.','astromae-real.png','https://astromae.vercel.app'],['Gambito Streetwear','Marca · E-commerce · Cultura','Streetwear inspirado em xadrez e jiu-jitsu.','gambito-real.png','https://gambito.vercel.app'],['Aurora','IA · Produto · Interface','Ambiente experimental de inteligência generativa.','aurora-real.png'],['Encantalente','Fotografia · Storytelling · Web','Portfólio fotográfico sobre gente vivendo.','encantalente-real.png'],['Ipê Massoterapia','Bem-estar · Marca · Site','Atendimento domiciliar em Brasília.','ipe-real.png'],['Nogueira Advocacia','Institucional · Conteúdo','Autoridade jurídica com conteúdo em vídeo.','nogueira-real.png'],['Stage & Speech','Educação · Comunidade','Clube de leitura dramática em inglês.','encantalente-real.png'],['Gigi — English & IT Coach','IA · Voz · FastAPI','Coach por voz para inglês de tecnologia.','astromae-real.png'],['Lembrança','Python · Desktop · Memória','Recupera datas de fotos e vídeos familiares.','encantalente.jpg'],['Pink Shift: Legacy','Unity · C# · Game design','Corrida cooperativa com física e aprendizagem.','broto.jpg'],['Aza Books','Editorial · Automação','Produção editorial bilíngue.','aza-books.webp'],['AppEsportes','Comunidade · Mapas','Produto esportivo com geolocalização.','gambito.jpeg'],['AfterShot','Visão computacional · Fotografia','Pipeline inteligente para ensaios.','encantalente-real.png'],['AIMA Reels','Agentes · Vídeo','Pipeline multiagente para Reels.','programadora.png'],['Radar Cultural','Dados · Cultura','Painel de editais e candidaturas.','aurora-real.png'],['Estúdio de Voz','TTS · Python · Áudio','Síntese neural e controle de voz.','astromae-real.png'],['Audition — Podcasts da Isa','Áudio · React','Estação criativa para podcasts.','gambito-real.png'],
['Ipê Studio','Web design · Marca · Brasília','Site autoral para massoterapia domiciliar.','ipe-studio.png'],['Aura Massoterapia','Bem-estar · Experiência','Presença digital para cuidado corporal.','aura-massoterapia.png'],['O Caibalion','Editorial · Filosofia','Leitura imersiva dos princípios herméticos.','caibalion.png'],['Currículo Isa','Carreira · Web design · IA','Currículo-portfólio experimental.','curriculo-isa.png'],['DEVISA','Experiência sensorial','Interface feita de ritmo, cor e movimento.','devisa.png'],['Editora Eixinho','Editorial · Infância','Histórias que encantam e educam.','eixinho.png'],['Esporte Brasília','Comunidade · Esporte','Esporte conectado à vida urbana.','esporte-brasilia.png'],['Guia de Estudos Criativo','Educação · UX','Jornada visual de organização e estudo.','guia-estudos.png'],['Iso — Invista com IA','Finanças · IA','Investimento assistido por inteligência artificial.','invista-ia.png'],['Reino das Notas Mágicas','Game · Música','Notas musicais viram aventura.','cecilia-notas.png'],['Corrida da Praia','Game · Infância','Jogo de corrida feito para Cecília.','cecilia-praia.png'],['Dojo da Mente','Jogos · Aprendizagem','Desafios de atenção, lógica e criatividade.','dojo-mente.png'],['Luna and the Stars She Named','Livro · Girls Who Dream','Experiência bilíngue do livro infantil.','luna-stars.png'],['Quiz Estilo de Luz','Fotografia · Quiz','Personalidade traduzida em fotografia.','quiz-luz.png']];
const verifiedLinks={BROTO:'https://broto-investimentos-a-es.vercel.app','AstroMãe':'https://astromae-sigma.vercel.app','Stage & Speech':'https://stage-and-speech-nine.vercel.app','Esporte Brasília':'https://esportebsb-omega.vercel.app'};
projects.forEach(p=>{if(verifiedLinks[p[0]])p[4]=verifiedLinks[p[0]];if(p[0]==='Gambito Streetwear')p.length=4});
const programaDora=projects.find(p=>p[0]==='ProgramaDora');if(programaDora){programaDora[0]='ProgramaDora — Blog de Tecnologia';programaDora[1]='Blog · Web design · IA · Automação';programaDora[2]='Blog autoral sobre front-end, web design, IA, marketing digital, automações e ética, com pesquisa e validação automatizadas.';}
projects.push(
['App Ceci','React · Infância · Produto','Aplicativo lúdico construído para experiências e rotinas da Cecília.','voice-tech.svg'],
['Motivation Lab','Web · Storytelling · Motivação','Coleção digital de projetos de motivação, propósito e desenvolvimento pessoal.','voice-tech.svg'],
['Computação Gráfica Lab','Python · Visão computacional · Áudio','Laboratório de face swap, processamento visual e conversão de voz.','voice-tech.svg'],
['Encanta Experience','React · Motion · Experiência','Experiência web experimental da marca Encanta com componentes e movimento.','voice-tech.svg'],
['ENIT Pipeline','Python · Streamlit · Automação','Pipeline técnico com interface premium para processamento e orquestração de tarefas.','voice-tech.svg'],
['Portal Espiritual','React · Filosofia · Experiência','Produto digital que conecta reflexão, espiritualidade e linguagem interativa.','voice-tech.svg'],
['Game Lab React','React · TypeScript · Games','Laboratório de mecânicas de jogo construído com React e TypeScript.','voice-tech.svg'],
['Aventura da Cecília','JavaScript · Game design · Infância','Aventura web infantil criada com narrativa, interação e progressão.','voice-tech.svg'],
['Cobrinha dos Brócolis','JavaScript · Canvas · Game design','Releitura infantil do jogo da cobrinha com identidade e objetivos próprios.','voice-tech.svg'],
['Secretaria Encantalente','Web · Fotografia · Operações','Interface de secretaria para organizar a operação do estúdio fotográfico.','voice-tech.svg'],
['Edital em Foco','Python · OCR · Documentos','Ferramenta para extrair, localizar e organizar informações de editais extensos.','voice-tech.svg'],
['Base de Conhecimento SUAS','Dados · Pesquisa · Serviço público','Acervo estruturado de legislação, políticas e conceitos do sistema socioassistencial.','voice-tech.svg'],
['CM Intelligence','Fintech · Dados · Estratégia','Arquitetura de inteligência financeira baseada em evidências, memória e auditoria.','voice-tech.svg'],
['Instagram AI Guide Builder','Python · Automação editorial · PDF','Sistema que transforma pesquisa e conteúdo em guias visuais prontos para publicação.','voice-tech.svg'],
['Radar LinkedIn & Concursos','Python · Pesquisa · Relatórios','Rotina de pesquisa, relatórios profissionais e acompanhamento de concursos.','voice-tech.svg']
);
const grid=document.querySelector('#grid');grid.innerHTML=projects.map((p,i)=>`<article class="card fx-${i%8}"><div class="shot"><div class="bar"><i></i><i></i><i></i><small>PROJETO ${String(i+1).padStart(2,'0')}</small></div><img src="/showcase/${p[3]}" alt="Interface real de ${p[0]}"><b class="scan"></b><b class="prism"></b></div><small>${p[1]}</small><h3 data-text="${p[0]}">${p[0]}</h3><p>${p[2]}</p>${p[4]?`<a class="magnetic" href="${p[4]}" target="_blank">VISITAR SITE ↗</a>`:'<b class="local">PROTÓTIPO LOCAL</b>'}</article>`).join('');
document.body.insertAdjacentHTML('afterbegin','<div class="loader"><b>ISADORA</b><i></i></div><canvas id="particles"></canvas><div class="spotlight"></div><div class="trail"></div><div class="trail t2"></div>');
const reduce=matchMedia('(prefers-reduced-motion:reduce)').matches,io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.06});document.querySelectorAll('section,.card').forEach(x=>io.observe(x));
addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader').classList.add('done'),450));addEventListener('scroll',()=>{progress.style.width=scrollY/(document.body.scrollHeight-innerHeight)*100+'%';document.documentElement.style.setProperty('--sy',scrollY+'px')},{passive:true});
let mx=0,my=0,tx=0,ty=0;addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY;cursor.style.transform=`translate(${mx}px,${my}px)`;document.documentElement.style.setProperty('--mx',mx+'px');document.documentElement.style.setProperty('--my',my+'px')},{passive:true});function trail(){tx+=(mx-tx)*.09;ty+=(my-ty)*.09;document.querySelector('.trail').style.transform=`translate(${tx}px,${ty}px)`;document.querySelector('.t2').style.transform=`translate(${tx+(mx-tx)*.35}px,${ty+(my-ty)*.35}px)`;requestAnimationFrame(trail)}if(!reduce)trail();
document.querySelectorAll('.shot').forEach(el=>{el.addEventListener('pointermove',e=>{let r=el.getBoundingClientRect();el.style.setProperty('--px',(e.clientX-r.left)/r.width);el.style.setProperty('--py',(e.clientY-r.top)/r.height);el.style.transform=`perspective(1100px) rotateX(${-(e.clientY-r.top-r.height/2)/r.height*9}deg) rotateY(${(e.clientX-r.left-r.width/2)/r.width*11}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
document.querySelectorAll('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{let r=el.getBoundingClientRect();el.style.translate=`${(e.clientX-r.left-r.width/2)*.18}px ${(e.clientY-r.top-r.height/2)*.18}px`}));
const c=document.querySelector('#particles'),x=c.getContext('2d'),dots=Array.from({length:55},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,v:.2+Math.random()*.6,r:.4+Math.random()*1.4}));function draw(){c.width=innerWidth;c.height=innerHeight;x.clearRect(0,0,c.width,c.height);x.fillStyle='#dfff0065';dots.forEach(d=>{d.y-=d.v;if(d.y<0)d.y=c.height;x.beginPath();x.arc(d.x,d.y,d.r,0,7);x.fill()});requestAnimationFrame(draw)}if(!reduce)draw();
setTimeout(()=>document.querySelector('.loader')?.classList.add('done'),1800);
const detailsScript=document.createElement('script');detailsScript.src='/details.js';document.body.append(detailsScript);
const playgroundStyle=document.createElement('link');playgroundStyle.rel='stylesheet';playgroundStyle.href='/playground-robot-fix.css';document.head.append(playgroundStyle);
const playgroundScript=document.createElement('script');playgroundScript.src='/playground.js';document.body.append(playgroundScript);
