const posts=[
['React','Composição antes de abstração','Componentes melhores nascem de responsabilidades pequenas e contratos explícitos.','Mapeie estados, eventos e dados antes de criar uma abstração reutilizável.','Refatore um componente grande em três unidades testáveis.'],
['React','Estado derivado não precisa de useEffect','Reduzir sincronizações evita renderizações extras e bugs difíceis de rastrear.','Calcule valores durante o render ou use memoização somente quando houver custo real.','Localize um effect que apenas copia props para state.'],
['Next.js','Server e Client Components sem confusão','A fronteira correta reduz JavaScript no navegador e melhora a arquitetura.','Mantenha busca de dados e conteúdo estático no servidor; mova só interação para o cliente.','Marque as fronteiras client do seu projeto atual.'],
['Next.js','Cache como decisão de produto','Cache não é só performance: define quão recente uma informação precisa ser.','Documente para cada rota o custo de desatualização e a estratégia de revalidação.','Crie uma matriz rota, origem, TTL e invalidação.'],
['TypeScript','Tipos que modelam estados impossíveis','Uma boa união discriminada impede combinações inválidas antes da execução.','Modele loading, success e error como variantes, não como três booleanos.','Reescreva um estado assíncrono usando union types.'],
['TypeScript','unknown é uma ferramenta de segurança','Dados externos não são confiáveis até serem validados.','Receba payloads como unknown e valide na borda com schema ou type guards.','Valide a resposta de uma API usada no portfólio.'],
['JavaScript','Event loop para interfaces mais fluidas','Entender tarefas, microtarefas e frames ajuda a evitar travamentos.','Divida trabalho pesado, use requestAnimationFrame para animações e meça long tasks.','Analise uma interação no painel Performance.'],
['JavaScript','Módulos com baixo acoplamento','Dependências explícitas tornam código mais fácil de testar e substituir.','Prefira funções que recebem dependências a módulos que acessam globais escondidos.','Transforme uma dependência global em parâmetro.'],
['UX/UI','Hierarquia visual é arquitetura da atenção','Tamanho, contraste e espaço determinam o caminho de leitura.','Defina uma ação primária por tela e reduza competição visual ao redor dela.','Faça o teste de desfoque em uma página.'],
['UX/UI','Estados vazios também são produto','Uma tela sem dados deve explicar o contexto e oferecer um próximo passo.','Projete estados vazio, carregando, erro, sucesso e permissão negada juntos.','Adicione um estado vazio útil a um projeto.'],
['Acessibilidade','Teclado primeiro revela problemas cedo','Se a jornada funciona por teclado, estrutura e foco tendem a estar melhores.','Use elementos semânticos, foco visível e ordem de tabulação coerente.','Complete o fluxo principal sem tocar no mouse.'],
['Acessibilidade','Motion com consentimento do sistema','Movimento pode informar, mas também causar desconforto.','Respeite prefers-reduced-motion e preserve significado sem depender da animação.','Teste o portfólio com movimento reduzido.'],
['Performance','Core Web Vitals como sintomas','LCP, INP e CLS apontam gargalos percebidos por pessoas reais.','Relacione cada métrica a uma hipótese e confirme antes de otimizar.','Registre uma linha de base das páginas principais.'],
['Performance','Imagens responsivas sem desperdício','Formato, dimensões e prioridade corretos reduzem transferência e melhoram LCP.','Entregue tamanhos adequados ao viewport e não carregue tudo antecipadamente.','Audite as cinco imagens mais pesadas.'],
['APIs','Contratos resilientes entre frontend e backend','Interfaces confiáveis tratam atraso, ausência, erro e mudanças de schema.','Centralize clientes HTTP, normalize erros e valide respostas externas.','Crie um tipo comum de erro para a aplicação.'],
['APIs','Idempotência evita ações duplicadas','Repetir uma requisição não deveria criar cobranças ou registros extras.','Use chaves idempotentes em mutações críticas e desabilite reenvios acidentais.','Mapeie as mutações que precisam de proteção.'],
['Git/GitHub','Commits contam decisões','Histórico útil explica intenção e permite revisar mudanças com confiança.','Faça commits pequenos, com mensagem orientada ao resultado.','Divida sua próxima feature em três commits coerentes.'],
['Git/GitHub','README como primeira interface','O repositório começa antes do usuário executar o código.','Mostre problema, solução, stack, arquitetura, instalação, imagens e decisões.','Melhore o README do projeto que mais representa você.'],
['Deploy/DevOps','Preview deployments aceleram feedback','Cada mudança pode virar um ambiente revisável antes da produção.','Use previews para validar conteúdo, responsividade e integração com dados.','Associe uma checklist curta ao próximo preview.'],
['Deploy/DevOps','Variáveis de ambiente por contexto','Configuração segura muda entre desenvolvimento, preview e produção.','Nunca versione segredos; documente apenas nomes e exemplos não sensíveis.','Revise o histórico por credenciais expostas.'],
['IA aplicada','RAG não corrige fonte ruim','Recuperação aumenta acesso ao contexto, mas não garante qualidade factual.','Curadoria, chunking, metadados e avaliação importam tanto quanto o modelo.','Crie cinco perguntas de teste para sua base.'],
['IA aplicada','Evals antes de trocar o modelo','Sem casos de teste, comparar modelos vira impressão subjetiva.','Colete exemplos reais, critérios claros e falhas importantes.','Monte um conjunto mínimo de dez casos.'],
['IA aplicada','Human in the loop como design','Revisão humana deve acontecer no ponto de maior risco ou ambiguidade.','Mostre evidências, nível de confiança e permita correção antes da ação externa.','Desenhe um checkpoint para um fluxo automatizado.'],
['Dados','Métrica sem decisão é decoração','Uma métrica útil muda uma escolha, prioridade ou comportamento.','Defina pergunta, unidade, janela temporal e ação associada.','Remova um número que não orienta nenhuma decisão.'],
['Dados','Qualidade começa na coleta','Dados ausentes, duplicados ou enviesados contaminam toda análise posterior.','Valide schema, faixa, unicidade, origem e atualização na entrada.','Crie cinco regras de qualidade para seu dataset.'],
['Automação','Automatize o repetível, preserve o julgamento','Automação funciona melhor em tarefas estáveis e verificáveis.','Separe coleta, transformação, validação e publicação em etapas observáveis.','Identifique o ponto que ainda exige decisão humana.'],
['Automação','Retries precisam de limites','Repetir cegamente pode multiplicar custo e dano.','Use backoff, limite de tentativas, idempotência e fila de falhas.','Documente a política de retry de uma integração.'],
['Segurança','Segredos nunca pertencem ao frontend','Tudo que chega ao navegador pode ser visto pelo usuário.','Mova chaves privadas para funções de servidor e aplique menor privilégio.','Procure chaves hardcoded antes do próximo deploy.'],
['Segurança','Autorização não é só autenticação','Saber quem entrou não define o que essa pessoa pode fazer.','Valide permissão no servidor para cada recurso e ação sensível.','Crie uma matriz papel versus ação.'],
['Arquitetura','Bordas claras reduzem complexidade','Sistemas sustentáveis separam domínio, infraestrutura e interface.','Mantenha regras de negócio independentes do framework quando fizer sentido.','Extraia uma regra hoje presa a um componente.'],
['Arquitetura','Comece simples, registre decisões','Arquitetura evolutiva evita tanto improviso quanto complexidade precoce.','Use registros curtos de decisão com contexto, escolha e consequências.','Escreva o primeiro ADR de um projeto.'],
['Testes','Teste comportamento, não implementação','Testes resistentes verificam o que a pessoa percebe e o contrato promete.','Priorize fluxos críticos e resultados observáveis.','Escreva um teste para a principal jornada do usuário.'],
['Testes','A pirâmide depende do risco','Unidade, integração e ponta a ponta cobrem falhas diferentes.','Invista mais onde o custo da regressão é maior.','Liste três riscos e o teste adequado para cada um.'],
['Produto','Portfólio mostra raciocínio, não só telas','Contratantes querem entender problema, papel, decisões e resultado.','Transforme cada projeto em um estudo de caso com evidências.','Escreva o antes, decisão e depois de um projeto.'],
['Produto','Escopo é uma habilidade técnica','Entregar a menor solução coerente cria aprendizado mais rápido.','Defina objetivo, não objetivos e critério de pronto antes de codar.','Reduza uma ideia atual ao primeiro resultado demonstrável.'],
['Carreira','Especialidade com amplitude tem forma de T','Profundidade em frontend ganha força com visão de produto, dados e IA.','Escolha um eixo principal e use as áreas vizinhas como multiplicadores.','Defina sua frase profissional em uma linha.'],
['Carreira','Evidência vence lista de tecnologias','Resultados, decisões e código acessível tornam competência verificável.','Ligue cada habilidade a um projeto, desafio ou métrica concreta.','Troque cinco adjetivos do currículo por evidências.'],
['Comunicação','Explicar trade-offs demonstra senioridade','Decisões técnicas raramente têm uma resposta universal.','Apresente contexto, opções, escolha, custo e condição para revisar.','Grave uma explicação de dois minutos sobre uma decisão.'],
['English Tech','Leia documentação como investigação','Inglês técnico melhora quando está ligado a uma pergunta real.','Leia primeiro títulos, exemplos e tipos; depois aprofunde no trecho necessário.','Resuma uma página de documentação em inglês.'],
['English Tech','Vocabulário ativo nasce em contexto','Memorizar termos isolados transfere pouco para reuniões e código.','Colete frases reais de issues, PRs e documentação e reutilize-as.','Escreva um comentário de PR em inglês hoje.']
];
posts.forEach(p=>{if(p[0]==='React'||p[0]==='Next.js')p[0]='Frontend React/Next';if(p[0]==='Comunicação'||p[0]==='English Tech')p[0]='Comunicação/English'});
const categories=[...new Set(posts.map(p=>p[0]))];
const references={
'Frontend React/Next':[['React: Thinking in React','https://react.dev/learn/thinking-in-react'],['Next.js: Server e Client Components','https://nextjs.org/docs/app/getting-started/server-and-client-components'],['Comunidade oficial React','https://react.dev/community']],
'TypeScript':[['TypeScript Handbook: Narrowing','https://www.typescriptlang.org/docs/handbook/2/narrowing.html'],['TypeScript: Everyday Types','https://www.typescriptlang.org/docs/handbook/2/everyday-types.html'],['TypeScript no Stack Overflow','https://stackoverflow.com/questions/tagged/typescript']],
'JavaScript':[['MDN: modelo de concorrência e event loop','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model'],['MDN: JavaScript Modules','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules'],['TC39: propostas da linguagem','https://github.com/tc39/proposals']],
'UX/UI':[['Nielsen Norman Group: heurísticas','https://www.nngroup.com/articles/ten-usability-heuristics/'],['Material Design 3','https://m3.material.io/'],['Laws of UX','https://lawsofux.com/']],
'Acessibilidade':[['W3C: WCAG 2.2','https://www.w3.org/TR/WCAG22/'],['MDN: Accessibility','https://developer.mozilla.org/en-US/docs/Web/Accessibility'],['WebAIM: recursos e comunidade','https://webaim.org/resources/']],
'Performance':[['web.dev: Core Web Vitals','https://web.dev/articles/vitals'],['MDN: Web Performance','https://developer.mozilla.org/en-US/docs/Web/Performance'],['Vercel: Speed Insights','https://vercel.com/docs/speed-insights']],
'APIs':[['MDN: visão geral do HTTP','https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview'],['RFC 9110: semântica HTTP','https://www.rfc-editor.org/rfc/rfc9110'],['Postman Community','https://community.postman.com/']],
'Git/GitHub':[['Pro Git — livro aberto','https://git-scm.com/book/en/v2'],['GitHub Docs: colaborar com pull requests','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests'],['GitHub Community','https://github.com/orgs/community/discussions']],
'Deploy/DevOps':[['Vercel: Deployments','https://vercel.com/docs/deployments'],['The Twelve-Factor App: Config','https://12factor.net/config'],['GitHub Actions Docs','https://docs.github.com/en/actions']],
'IA aplicada':[['NIST: AI Risk Management Framework','https://www.nist.gov/itl/ai-risk-management-framework'],['OpenAI: avaliação de modelos','https://platform.openai.com/docs/guides/evals'],['RAG — artigo original','https://arxiv.org/abs/2005.11401']],
'Dados':[['Google: Data Validation','https://research.google/pubs/data-validation-for-machine-learning/'],['Great Expectations Docs','https://docs.greatexpectations.io/'],['Kaggle Learn: Data Cleaning','https://www.kaggle.com/learn/data-cleaning/course']],
'Automação':[['Temporal: Retry Policies','https://docs.temporal.io/encyclopedia/retry-policies'],['AWS: retries com backoff','https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/retry-backoff.html'],['Martin Fowler: Continuous Integration','https://martinfowler.com/articles/continuousIntegration.html']],
'Segurança':[['OWASP Top 10','https://owasp.org/www-project-top-ten/'],['OWASP: Secrets Management','https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html'],['MDN: Web Security','https://developer.mozilla.org/en-US/docs/Web/Security']],
'Arquitetura':[['C4 Model','https://c4model.com/'],['Architecture Decision Records','https://adr.github.io/'],['Martin Fowler: Software Architecture Guide','https://martinfowler.com/architecture/']],
'Testes':[['Testing Library: princípios','https://testing-library.com/docs/guiding-principles'],['Playwright: melhores práticas','https://playwright.dev/docs/best-practices'],['Google Testing Blog','https://testing.googleblog.com/']],
'Produto':[['Shape Up — Basecamp','https://basecamp.com/shapeup'],['Nielsen Norman Group: UX Research','https://www.nngroup.com/articles/which-ux-research-methods/'],['Atlassian: Product Management','https://www.atlassian.com/agile/product-management']],
'Carreira':[['MDN Curriculum','https://developer.mozilla.org/en-US/curriculum/'],['GitHub Docs: Profile README','https://docs.github.com/en/account-and-profile/how-tos/profile-customization/managing-your-profile-readme'],['Stack Overflow Developer Survey','https://survey.stackoverflow.co/']],
'Comunicação/English':[['Google Technical Writing','https://developers.google.com/tech-writing'],['GitHub: revisão de mudanças','https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests'],['RFC Editor','https://www.rfc-editor.org/']]
};
function article(p){const refs=references[p[0]]||[];return `<button class="article-close" aria-label="Fechar">×</button><small>${p[0]} · ARTIGO APLICÁVEL</small><h1>${p[1]}</h1><p class="article-lead">${p[2]}</p><h2>O problema por trás da técnica</h2><p>${p[3]} Em projetos reais, a dificuldade não costuma ser conhecer uma API isolada, mas decidir onde aplicá-la, como observar o resultado e quais consequências aceitar. Por isso, esta prática deve ser tratada como uma hipótese de engenharia: contexto claro, mudança pequena e evidência mensurável.</p><h2>Como aplicar</h2><p>Escolha uma jornada concreta do seu produto. Registre o comportamento atual, identifique o risco mais relevante e implemente a menor alteração que possa ser comparada. Observe impacto em clareza, manutenção, tempo de resposta ou experiência da pessoa usuária. Se o ganho não aparecer, reverta e documente o aprendizado — isso também é evolução técnica.</p><h2>No portfólio e em entrevistas</h2><p>Apresente o caso em quatro movimentos: problema, alternativas consideradas, decisão e resultado. Explique o trade-off sem transformar a ferramenta em protagonista. Esse formato demonstra raciocínio, domínio do contexto e capacidade de aprender com o sistema em produção.</p><h2>Laboratório de hoje</h2><p>${p[4]}</p><h2>Roteiro de verificação</h2><ul><li>Defina o problema e a pessoa afetada antes da tecnologia.</li><li>Crie um critério de sucesso que possa ser observado.</li><li>Implemente e compare a mudança em um caso real.</li><li>Registre limites, trade-offs e o próximo experimento.</li></ul><h2>Referências para aprofundar</h2><div class="article-refs">${refs.map((r,i)=>`<a href="${r[1]}" target="_blank" rel="noreferrer"><b>0${i+1}</b><span>${r[0]}</span> ↗</a>`).join('')}</div>`}
function render(filter='Todos'){const list=filter==='Todos'?posts:posts.filter(p=>p[0]===filter);document.querySelector('#posts').innerHTML=list.map((p,i)=>`<article class="post-card"><small>${p[0]} · ${String(posts.indexOf(p)+1).padStart(2,'0')}</small><h3>${p[1]}</h3><p>${p[2]}</p><button data-index="${posts.indexOf(p)}">LER ARTIGO ↗</button></article>`).join('');document.querySelectorAll('.post-card button').forEach(b=>b.onclick=()=>{const m=document.querySelector('.article-modal');m.querySelector('.article-inner').innerHTML=article(posts[+b.dataset.index]);m.classList.add('open');m.querySelector('.article-close').onclick=()=>m.classList.remove('open')})}
document.querySelector('#filters').innerHTML=['Todos',...categories].map((c,i)=>`<button class="${i?'':'active'}">${c}</button>`).join('');document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.textContent)});render();document.querySelector('.article-modal').onclick=e=>{if(e.target.classList.contains('article-modal'))e.currentTarget.classList.remove('open')};
const playgroundStyle=document.createElement('link');playgroundStyle.rel='stylesheet';playgroundStyle.href='/playground-robot-fix.css';document.head.append(playgroundStyle);
const playgroundScript=document.createElement('script');playgroundScript.src='/playground.js';document.body.append(playgroundScript);
