'use client';
import { useEffect, useRef } from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { projects } from './data';

function DreamCanvas(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current,x=c?.getContext('2d');if(!c||!x)return;let f=0,id=0,w=0,h=0;const size=()=>{const d=Math.min(devicePixelRatio,2);w=c.clientWidth;h=c.clientHeight;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0)};const draw=()=>{f+=.012;x.clearRect(0,0,w,h);const g=x.createLinearGradient(0,0,0,h);g.addColorStop(0,'#251053');g.addColorStop(.5,'#e332a1');g.addColorStop(1,'#ffb05c');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#fff';for(let i=0;i<75;i++){const px=(i*97+Math.sin(i)*40)%w,py=(i*53+f*30*(1+i%3))%Math.max(h*.58,1);x.globalAlpha=.25+(i%5)/8;x.fillRect(px,py,i%7===0?2:1,i%7===0?2:1)}x.globalAlpha=1;const horizon=h*.57;x.strokeStyle='#dfff00aa';for(let i=-10;i<=10;i++){x.beginPath();x.moveTo(w/2,horizon);x.lineTo(w/2+i*w*.13,h);x.stroke()}for(let i=0;i<18;i++){const p=(i/18+f*.13)%1,y=horizon+(h-horizon)*p*p;x.globalAlpha=p;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}x.globalAlpha=1;x.fillStyle='#0b0b0f';x.beginPath();x.arc(w*.72,horizon-18+Math.sin(f*2)*6,24,0,Math.PI*2);x.fill();x.strokeStyle='#fff';x.lineWidth=3;x.stroke();id=requestAnimationFrame(draw)};size();draw();addEventListener('resize',size);return()=>{cancelAnimationFrame(id);removeEventListener('resize',size)}},[]);return <canvas ref={ref} className="dream-canvas" aria-hidden="true"/>}

function StringCanvas(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current,x=c?.getContext('2d');if(!c||!x)return;let id=0,w=0,h=0,t=0;const p={x:.5,y:.5};const size=()=>{const d=Math.min(devicePixelRatio,2);w=c.clientWidth;h=c.clientHeight;c.width=w*d;c.height=h*d;x.setTransform(d,0,0,d,0,0)};const move=(e:PointerEvent)=>{const r=c.getBoundingClientRect();p.x=(e.clientX-r.left)/r.width;p.y=(e.clientY-r.top)/r.height};const draw=()=>{t+=.018;x.clearRect(0,0,w,h);for(let row=0;row<24;row++){x.beginPath();for(let col=0;col<=56;col++){const px=col*w/56,base=row*h/23,dx=px-p.x*w,dy=base-p.y*h,pull=Math.exp(-(dx*dx+dy*dy)/50000)*42,py=base+Math.sin(col*.34+t*2+row*.2)*7+pull*Math.sin(t+col*.1);col?x.lineTo(px,py):x.moveTo(px,py)}x.strokeStyle=`hsla(${285+row*4},100%,${55+row%4*5}%,.7)`;x.stroke()}id=requestAnimationFrame(draw)};size();draw();c.addEventListener('pointermove',move);addEventListener('resize',size);return()=>{cancelAnimationFrame(id);c.removeEventListener('pointermove',move);removeEventListener('resize',size)}},[]);return <canvas ref={ref} className="strings-canvas" aria-label="Campo generativo de linhas que reage ao cursor"/>}

export function CodepenEffects(){const move=(e:React.PointerEvent<HTMLDivElement>)=>{const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--mx',`${(e.clientX-r.left)/r.width-.5}`);e.currentTarget.style.setProperty('--my',`${(e.clientY-r.top)/r.height-.5}`)};return <section className="motion-lab"><DreamCanvas/><div className="motion-lab-copy"><span>[ 02 — MOTION LAB ]</span><h2>Ideias que não ficam <em>paradas.</em></h2><p>Três experimentos autorais inspirados em referências do CodePen: profundidade editorial, uma estrada procedural neon e cordas digitais responsivas.</p><Link href="/projetos">ENTRAR NO ACERVO <ArrowUpRight size={18}/></Link></div><div className="kinetic-word" aria-hidden="true"><span>M</span><span>O</span><span>V</span><span>E</span></div><div className="depth-stack" onPointerMove={move} onPointerLeave={e=>{e.currentTarget.style.setProperty('--mx','0');e.currentTarget.style.setProperty('--my','0')}}>{projects.slice(0,4).map((p,i)=><div className="depth-card" style={{'--i':i} as React.CSSProperties} key={p.name}><img src={p.image} alt=""/><strong>{p.name}</strong></div>)}</div><div className="strings-wrap"><StringCanvas/><div><small>INTERACTIVE / MOVE O CURSOR</small><strong>Sinais viram<br/>experiência.</strong></div></div></section>}
